name: Deno CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [2.1.7]

    steps:
      - uses: actions/checkout@v3

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: deno fmt --check
      - run: deno test --allow-none
